apps/products/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('Categories/', CategoriesView.as_view(), name='Categories'),
    path('Products/', ProductsView.as_view(), name='Products'),
    path('ProductsImage/', ProductsImageView.as_view(), name='ProductsImage'),

]

apps/user_profile/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('UserProfile/', UserProfile.as_view(), name='UserProfile')

]

core/urls.py
"""
URL configuration for fly_tour project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('products/', include('apps.products.urls')),
    path('reserv/', include('apps.reserv.urls')),
    path('user_profile/', include('apps.user_profile.urls')),

]

#
#
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

apps/products/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.db.models import Model
from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='products_images', blank=True, null=True, verbose_name='Изображение')
    population = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name='Популяция')
    territory = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name='Территория')
    continent = models.CharField(max_length=100, blank=True, null=True, verbose_name='Континент')


    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='products_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    is_active = models.BooleanField(default=True, verbose_name='Активный')
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'


class ProductsImage(models.Model):
    product = models.ForeignKey(Products, related_name='images', verbose_name='Продукты', on_delete=models.CASCADE)  # Измените 'image' на 'images'
    image = models.ImageField(verbose_name='Изображение', upload_to='dop_photo')

    class Meta:
        db_table = 'photos'
        verbose_name = 'Доп. фото'
        verbose_name_plural = 'Доп. фотки'

    def __str__(self):
        return str(self.image)

apps/user_profile/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.db.models import Model
from django.urls import reverse



class UserProfile(models.Model):
    image = models.ImageField(upload_to='profile_images', blank=True, null=True, verbose_name='фото')
    name = models.CharField(max_length=150, verbose_name='имя')
    last_name = models.CharField(max_length=150, verbose_name='фамилия')
    username = models.CharField(max_length=150, unique=True, verbose_name='имя пользователя')
    email = models.EmailField(max_length=254, unique=True, verbose_name='емайл')

    class Meta:
        db_table = 'user_profile'
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'

    def __str__(self):
        return self.username

apps/user_profile/forms.py
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django import forms



class UserProfileForm(UserCreationForm):
    username = forms.CharField(label='Username',widget=forms.TextInput(attrs={'class': ' form-control', 'placeholder': 'Username'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    image = forms.ImageField(widget=forms.imageInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    name = forms.CharField(label='Name',widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}))
    last_name = forms.CharField(label='Last_name',widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last_name'}))

    class Meta:
        model = UserProfile
        fields = ['username', 'email', 'image', ('last_name'), ('name')]

apps/products/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Products, ProductsImage, Categories

class CategoriesView(ListView):
    model = Categories
    template_name = 'pages/home.html'
    context_object_name = 'categories'

class ProductsImageView(ListView):
    model = ProductsImage
    template_name = 'pages/about.html'
    context_object_name = 'images'

class ProductsView(ListView):
    model = Products
    template_name = 'pages/about.html'
    context_object_name = 'products'
    queryset = Products.objects.all()

apps/user_profile/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView
from .models import UserProfile



class UserProfile(ListView):
    model = UserProfile
    template_name = 'pages/user_profile.html'
    context_object_name = 'user_profile'

templates/pages/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

  <!-- ***** Main Banner Area Start ***** -->
  <div class="about-main-content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="content">
            <div class="blur-bg"></div>
            <h4>ИЗУЧАЙТЕ НАШИ СТРАНЫ</h4>
            <div class="line-dec"></div>
            <h2>Добро пожаловать в наши страны</h2>
              <div class="main-button">
              <a href="{% url 'reservation' %}">Забронировать</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>




 <div class="cities-town">
    <div class="container">
      <div class="row">
        <div class="slider-content">
          <div class="row">
            <div class="col-lg-12">
              <h2>Города Карибского острова</h2>
            </div>
            <div class="col-lg-12">
              <div class="owl-cites-town owl-carousel">
                <div class="item">
                  <div class="thumb">
                    <img src="{% static 'assets/images/cities-01.jpg' %}" alt="">

                    <h4>Гавана</h4>
                  </div>
                </div>
                <div class="item">
                  <div class="thumb">
                    <img src="{% static 'assets/images/cities-02.jpg' %}" alt="">

                    <h4>Кингстон</h4>
                  </div>
                </div>
                <div class="item">
                  <div class="thumb">
                    <img src="{% static 'assets/images/cities-03.jpg' %}" alt="">

                    <h4>Джорджтаун</h4>
                  </div>
                </div>
                <div class="item">
                  <div class="thumb">
                    <img src="{% static 'assets/images/cities-04.jpg' %}" alt="">

                    <h4>Санто-Доминго</h4>
                  </div>
                </div>
                <div class="item">
                  <div class="thumb">
                    <img src="{% static 'assets/images/cities-01.jpg' %}" alt="">

                    <h4>Гавана</h4>
                  </div>
                </div>
                <div class="item">
                  <div class="thumb">
                    <img src="{% static 'assets/images/cities-02.jpg' %}" alt="">
                    <h4>Кингстон</h4>
                  </div>
                </div>
                <div class="item">
                  <div class="thumb">
                    <img src="{% static 'assets/images/cities-03.jpg' %}" alt="">
                    <h4>Джорджтаун</h4>
                  </div>
                </div>
                <div class="item">
                  <div class="thumb">
                    <img src="{% static 'assets/images/cities-04.jpg' %}" alt="">
                    <h4>Санто-Доминго</h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="weekly-offers">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 offset-lg-3">
          <div class="section-heading text-center">
            <h2>Лучшие еженедельные предложения</h2>
          </div>
        </div>
      </div>
    </div>




    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="owl-weekly-offers owl-carousel">



            <div class="item">
              <div class="thumb">
                <img src="{% static 'assets/images/offers-01.jpg' %}" alt="">
                <div class="text">
                  <h4>Турция<br></h4>
                  <h6>$420<br><span>/person</span></h6>
                  <div class="line-dec"></div>
                  <ul>
                    <li>Сделка включает в себя:</li>
                    <li><i class="fa fa-taxi"></i> 5-дневная поездка > Отель включен</li>
                    <li><i class="fa fa-plane"></i> Счет за самолет включен в стоимость</li>
                    <li><i class="fa fa-building"></i> Ежедневное посещение мест</li>
                  </ul>
                  <div class="main-button">
                    <a href="{% url 'reservation' %}">Забронировать</a>
                  </div>
                </div>
              </div>
            </div>


            <div class="item">
              <div class="thumb">
                <img src="{% static 'assets/images/offers-03.jpg' %}" alt="">
                <div class="text">
                  <h4>Италия<br></h4>
                  <h6>$500<br><span>/person</span></h6>
                  <div class="line-dec"></div>
                  <ul>
                    <li>Сделка включает в себя:</li>
                    <li><i class="fa fa-taxi"></i> 5-дневная поездка > Отель включен</li>
                    <li><i class="fa fa-plane"></i> Счет за самолет включен в стоимость</li>
                    <li><i class="fa fa-building"></i>Ежедневное посещение мест</li>
                  </ul>
                  <div class="main-button">
                    <a href="{% url 'reservation' %}">Забронировать</a>
                  </div>
                </div>
              </div>
            </div>



            <div class="item">
              <div class="thumb">
                <img src="{% static 'assets/images/offers-02.jpg' %}" alt="">
                <div class="text">
                  <h4>Россия<br></h4>
                  <h6>$600<br><span>/person</span></h6>
                  <div class="line-dec"></div>
                  <ul>
                    <li>Сделка включает в себя:</li>
                    <li><i class="fa fa-taxi"></i> 5-дневная поездка > Отель включен</li>
                    <li><i class="fa fa-plane"></i> Счет за самолет включен в стоимость</li>
                    <li><i class="fa fa-building"></i> Ежедневное посещение мест</li>
                  </ul>
                  <div class="main-button">
                    <a href="{% url 'reservation' %}">Забронировать</a>
                  </div>
                </div>
              </div>
            </div>



            <div class="item">
              <div class="thumb">
                <img src="{% static 'assets/images/deals-01.jpg' %}" alt="">
                <div class="text">
                  <h4>Англия<br></h4>
                  <h6>$950<br><span>/person</span></h6>
                  <div class="line-dec"></div>
                  <ul>
                    <li>Сделка включает в себя:</li>
                    <li><i class="fa fa-taxi"></i> 5-дневная поездка > Отель включен</li>
                    <li><i class="fa fa-plane"></i> Счет за самолет включен в стоимость</li>
                    <li><i class="fa fa-building"></i> Ежедневное посещение мест</li>
                  </ul>
                  <div class="main-button">
                    <a href="{% url 'reservation' %}">Забронировать</a>
                  </div>
                </div>
              </div>
            </div>



            <div class="item">
              <div class="thumb">
                <img src="{% static 'assets/images/deals-02.jpg' %}" alt="">
                <div class="text">
                  <h4>Тайланд<br></h4>
                  <h6>$480<br><span>/person</span></h6>
                  <div class="line-dec"></div>
                  <ul>
                    <li>Сделка включает в себя:</li>
                    <li><i class="fa fa-taxi"></i> 5-дневная поездка > Отель включен</li>
                    <li><i class="fa fa-plane"></i> Счет за самолет включен в стоимость</li>
                    <li><i class="fa fa-building"></i> Ежедневное посещение мест</li>
                  </ul>
                  <div class="main-button">
                    <a href="{% url 'reservation' %}">Забронировать</a>
                  </div>
                </div>
              </div>
            </div>




            <div class="item">
              <div class="thumb">
                <img src="{% static 'assets/images/deals-03.jpg' %}" alt="">
                <div class="text">
                  <h4>Греция<br></h4>
                  <h6>$780<br><span>/person</span></h6>
                  <div class="line-dec"></div>
                  <ul>
                    <li>Сделка включает в себя:</li>
                    <li><i class="fa fa-taxi"></i> 5-дневная поездка > Отель включен</li>
                    <li><i class="fa fa-plane"></i> Счет за самолет включен в стоимость</li>
                    <li><i class="fa fa-building"></i> Ежедневное посещение мест</li>
                  </ul>
                  <div class="main-button">
                    <a href="{% url 'reservation' %}">Забронировать</a>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>












<div class="more-about">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <div class="left-image">
            <img src="{% static 'assets/images/q.jpg' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="section-heading">
            <h2>Узнайте больше о нашей стране</h2>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="info-item">
                <h4>150.640 +</h4>
                <span>Всего гостей в год</span>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="info-item">
                <h4>175.000+</h4>
                <span>Удивительные условия проживания</span>
              </div>
            </div>
            <div class="col-lg-12">
              <div class="info-item">
                <div class="row">
                  <div class="col-lg-6">
                    <h4>12.560+</h4>
                    <span>Удивительные места</span>
                  </div>
                  <div class="col-lg-6">
                    <h4>240.580+</h4>
                    <span>Различные регистрации ежегодно</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="main-button">
            <a href="{% url 'reservation' %}">Узнайте больше</a>
          </div>
        </div>
      </div>
    </div>
  </div>










<!--   <div class="call-to-action">-->
<!--    <div class="container">-->
<!--      <div class="row">-->
<!--        <div class="col-lg-8">-->
<!--          <h2>Вы хотите путешествовать?</h2>-->
<!--          <h4>Сделайте заказ, нажав кнопку</h4>-->
<!--        </div>-->
<!--        <div class="col-lg-4">-->
<!--          <div class="border-button">-->
<!--            <a href="{% url 'reservation' %}">забронируй сейчас</a>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->


{% endblock %}

templates/pages/login.html
{% extends 'base.html' %}

{% block content %}


<style>
.bg-blue {
    background-color: #6f42c1; /* Синий цвет */
  }
</style>

<section class="bg-purple py-12 py-md-12 py-xl-12">
    <div class="container">
      <div class="row gy-12 align-items-center">


        <div class="col-12 col-md-6 col-xl-5">
          <div class="card border-0 rounded-4" style="left: 350px;">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="row">
                <div class="col-12">
                  <div class="mb-4">
                    <h3>Войти</h3>
<!--                    <p>У вас нет учетной записи?<a href="{% url 'register' %}">Зарегистрироваться</a></p>-->
                  </div>
                </div>
              </div>
              <form method="post" action="">
                {% csrf_token %}
                <div class="row gy-3 overflow-hidden">
                    <div class="col-12">
                      <div class="form-floating mb-3">
                          {{ form.username }}
                          <label for="username">Имя пользователя</label>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="form-floating mb-3">
                          {{ form.email }}
                          <label for="email">Электронная почта</label>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="form-floating mb-3">
                          {{ form.password }}
                          <label for="password">Пароль</label>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="d-grid">
                          <button class="btn btn-primary btn-lg" type="submit">Login</button>
                      </div>
                    </div>
                </div>
            </form>


<!-- <div class="call-to-action">-->
<!--    <div class="container">-->
<!--      <div class="row">-->
<!--        <div class="col-lg-8">-->
<!--          <h2>Вы хотите путешествовать?</h2>-->
<!--          <h4>Сделайте заказ, нажав кнопку</h4>-->
<!--        </div>-->
<!--        <div class="col-lg-4">-->
<!--          <div class="border-button">-->
<!--            <a href="{% url 'reservation' %}">забронируй сейчас</a>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->

{% endblock %}

templates/pages/register.html
{% extends 'base.html' %}

{% block content %}


<style>
.bg-purple {
    background-color: #6f42c1; /* Фиолетовый цвет */
  }
</style>


<section class="bg-blue py-3 py-md-5 py-xl-8">
    <div class="container">
      <div class="row gy-4 align-items-center">
        <div class="col-12 col-md-6 col-xl-7">
          <div class="d-flex justify-content-center text-bg-primary">

          </div>
        </div>
        <div class="col-12 col-md-6 col-xl-5">
          <div class="card border-0 rounded-4">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="row">
                <div class="col-12">
                  <div class="mb-4">
                    <h3>Зарегистрироваться</h3>
                    <p>У вас нет учетной записи?<a href="#!">Зарегистрироваться</a></p>
                  </div>
                </div>
              </div>
              <form action="{% url 'register' %}" method="post">
                {% csrf_token %}

                <!-- Обработка ошибок  -->
                {% if form.errors %}
                  <div class="alert alert-danger">
                    <strong>Please fix the following errors:</strong>
                    <ul>
                      {% for field in form %}
                        {% for error in field.errors %}
                          <li>{{ error|escape }}</li>
                        {% endfor %}
                      {% endfor %}
                    </ul>
                  </div>
                {% endif %}
                <div class="row gy-3 overflow-hidden">
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{form.username}}
                      <label for="username">Имя пользователя</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{form.email}}
                      <label for="email">Электронная почта</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{form.password1}}
                      <label for="password">Пароль</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{form.password2}}
                      <label for="password2">Пароль2</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" name="remember_me" id="remember_me">
                      <label class="form-check-label text-secondary" for="remember_me">
                        Не выходить из системы
                      </label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-grid">
                      <button class="btn btn-primary btn-lg" type="submit">Зарегистрируйтесь сейчас</button>
                    </div>
                  </div>
                </div>
              </form>
              <div class="row">
                <div class="col-12">
                  <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-end mt-4">
                    <a href="#!">Забыли пароль</a>
                  </div>
                </div>
              </div>


{% endblock %}

templates/pages/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="{% url "user_profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static "deps/images/baseavatar.jpg" %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name='image'
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя"
                                    value="{{ form.first_name.value }}"
                                    required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию"
                                    value="{{ form.last_name.value }}"
                                    required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя"
                                    value="{{ form.username.value }}"
                                    required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    value="{{ form.email.value }}"
                                    required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
<!-- <div class="call-to-action">-->
<!--    <div class="container">-->
<!--      <div class="row">-->
<!--        <div class="col-lg-8">-->
<!--          <h2>Вы хотите путешествовать?</h2>-->
<!--          <h4>Сделайте заказ, нажав кнопку</h4>-->
<!--        </div>-->
<!--        <div class="col-lg-4">-->
<!--          <div class="border-button">-->
<!--            <a href="{% url 'reservation' %}">забронируй сейчас</a>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
{% endblock  %}